### ISSUE TITLE
Docker cp error

### ISSUE THREAD

**Issue by jamesh48** [RyterINC/nacl-package-builder#1]
Hi, 

I installed Docker on my local machine and followed the steps

The last step is the only one that errors

unknown flag: --help'.:/tmp/pynacl_layer.zip
See 'docker cp --help'.

Do you have any insight?

**Comment by jamesh48** [comment]
It got it to work but I had to login to the container and manually run each command from the Dockerfile- one at a time

**Comment by jamesh48** [comment]
Thank you by the way!

**Comment by RyterINC** [comment]
Glad it is working for you! sorry I didn't see this yesterday.

**Comment by jamesh48** [comment]
No worries, if it wasn't due to the fact of using macos or just me being a complete newbie to docker (most likely- I installed it for the first time for this purpose expressly), my sense was that the script was not installing the package in the docker container- maybe theres an async issue with the command in the Dockerfile? It looks like a hefty async command string- I wouldn't blame you if there was something small something that was missing or added for example- a `&` or a `/`

Also by the way, I had to run `docker ps` and pass the container id for the `docker cp` command directly instead of as a variable. There seemed to be a conflict with using the CONTAINER_ID variable, especially noticeable when I ran echo `$CONTAINER_ID`

But in total, I really appreciate this package- thank you!- it fit in perfectly with what the tutorial left out- I had been struggling with spawning and installing from an ec2 linux 2 instance for about 2-3 hours before I read the comments. Much appreciated :)

**Comment by RyterINC** [comment]
Yeah I haven't ran it in a while. I remember not having any issues when I
created it. I suppose I should test it again in a blank environment to keep
it up to date. Thanks for the feedback!

**Comment by RyterINC** [comment]
My latest commit fixes the above issues. For some reason, I was mounting my local directory as a volume over the containers /tmp directory, which was overwriting the package being produced. I've tested the new steps and built them from a clean environment and all seems to be working. Thanks for bringing up this issue.
